import { CardCollection, CardTemplate, Rarity } from '../types';

/* ========================================================================
   COLEÇÃO 1: OS QUATRO GUARDIÕES (4 CARTAS)
   ======================================================================== */
export const GUARDIANS_TEMPLATES: CardTemplate[] = [
  {
    templateId: 'card-flame-guardian',
    name: 'Guardião da Chama',
    element: 'fire',
    elementIcon: '🔥',
    description: 'Manifestação viva do fogo primordial que forjou as primeiras defesas cibernéticas da Cidadela.',
    image: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?w=800&auto=format&fit=crop&q=80',
    rarity: 'Incomum',
    collectionId: 'guardians',
    synthesisRate: 8,
    synthesisCap: 8000,
    marketValue: 120,
  },
  {
    templateId: 'card-ice-guardian',
    name: 'Guardião do Gelo',
    element: 'ice',
    elementIcon: '❄️',
    description: 'Entidade de zero absoluto que congela o fluxo temporal para preservar relíquias esquecidas.',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'guardians',
    synthesisRate: 10,
    synthesisCap: 10000,
    marketValue: 180,
  },
  {
    templateId: 'card-storm-guardian',
    name: 'Guardião da Tempestade',
    element: 'lightning',
    elementIcon: '⚡',
    description: 'Comandante de relâmpagos quânticos, acelera a sintetização através de pulso iônico concentrado.',
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    rarity: 'Épico',
    collectionId: 'guardians',
    synthesisRate: 15,
    synthesisCap: 15000,
    marketValue: 420,
  },
  {
    templateId: 'card-abyss-guardian',
    name: 'Guardião do Abismo',
    element: 'abyss',
    elementIcon: '🌑',
    description: 'O arauto da matéria escura. Extrai energia diretamente do vácuo quântico em rendimento sem precedentes.',
    image: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80',
    rarity: 'Lendário',
    collectionId: 'guardians',
    synthesisRate: 22,
    synthesisCap: 22000,
    marketValue: 980,
  },
];

/* ========================================================================
   COLEÇÃO 2: DRAGÕES ANCESTRAIS (8 CARTAS)
   ======================================================================== */
export const DRAGONS_TEMPLATES: CardTemplate[] = [
  {
    templateId: 'card-dragon-red',
    name: 'Dragão Rubro',
    element: 'fire',
    elementIcon: '🔥',
    description: 'Criação vulcânica ancestral cujas escamas emanam calor perpétuo capaz de fundir ligas de titânio.',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
    rarity: 'Incomum',
    collectionId: 'dragons',
    synthesisRate: 8,
    synthesisCap: 8000,
    marketValue: 130,
  },
  {
    templateId: 'card-dragon-frost',
    name: 'Dragão Glacial',
    element: 'ice',
    elementIcon: '❄️',
    description: 'Habitante das fendas criogênicas das cordilheiras de gelo eterno em Neo-Himalaia.',
    image: 'https://images.unsplash.com/photo-1491002052546-bf38f186af56?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'dragons',
    synthesisRate: 11,
    synthesisCap: 11000,
    marketValue: 200,
  },
  {
    templateId: 'card-dragon-emerald',
    name: 'Dragão Esmeralda',
    element: 'nature',
    elementIcon: '🌿',
    description: 'Ser protetor dos biomas cibernéticos sintéticos, revitaliza canais de dados corrompidos.',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    rarity: 'Incomum',
    collectionId: 'dragons',
    synthesisRate: 8,
    synthesisCap: 8000,
    marketValue: 140,
  },
  {
    templateId: 'card-dragon-shadow',
    name: 'Dragão Sombrio',
    element: 'dark',
    elementIcon: '🌑',
    description: 'Camufla-se nas sombras da sub-rede gerando distorções quânticas silenciosas.',
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'dragons',
    synthesisRate: 12,
    synthesisCap: 12000,
    marketValue: 240,
  },
  {
    templateId: 'card-dragon-gold',
    name: 'Dragão Dourado',
    element: 'light',
    elementIcon: '✨',
    description: 'Símbolo supremo de prosperidade no império de Eldoria, amplifica o fluxo de tokens NEX.',
    image: 'https://images.unsplash.com/photo-1533158307587-828f0a76ef46?w=800&auto=format&fit=crop&q=80',
    rarity: 'Épico',
    collectionId: 'dragons',
    synthesisRate: 16,
    synthesisCap: 16000,
    marketValue: 480,
  },
  {
    templateId: 'card-dragon-astral',
    name: 'Dragão Astral',
    element: 'astral',
    elementIcon: '🌌',
    description: 'Tecido a partir de poeira nebular e frequências cósmicas, viaja além da barreira da realidade.',
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&auto=format&fit=crop&q=80',
    rarity: 'Épico',
    collectionId: 'dragons',
    synthesisRate: 17,
    synthesisCap: 17000,
    marketValue: 550,
  },
  {
    templateId: 'card-dragon-volcanic',
    name: 'Dragão Vulcânico',
    element: 'fire',
    elementIcon: '🌋',
    description: 'Titã encouraçado nascido do magma central do planeta NEXA-Prime.',
    image: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    rarity: 'Lendário',
    collectionId: 'dragons',
    synthesisRate: 24,
    synthesisCap: 24000,
    marketValue: 1100,
  },
  {
    templateId: 'card-dragon-celestial',
    name: 'Dragão Celestial',
    element: 'celestial',
    elementIcon: '⭐',
    description: 'O dragão alfa do cosmo, soberano de todas as eras draconianas com capacidade máxima de síntese.',
    image: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80',
    rarity: 'Mítico',
    collectionId: 'dragons',
    synthesisRate: 32,
    synthesisCap: 32000,
    marketValue: 2400,
  },
];

/* ========================================================================
   COLEÇÃO 3: CAVALEIROS DE ELDORIA (8 CARTAS)
   ======================================================================== */
export const KNIGHTS_TEMPLATES: CardTemplate[] = [
  {
    templateId: 'card-knight-blade',
    name: 'Cavaleiro da Lâmina',
    element: 'light',
    elementIcon: '⚔️',
    description: 'Soldado de infantaria da guarda de Eldoria, treinado em combates de precisão com sabres laser.',
    image: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80',
    rarity: 'Comum',
    collectionId: 'knights',
    synthesisRate: 5,
    synthesisCap: 5000,
    marketValue: 60,
  },
  {
    templateId: 'card-knight-black',
    name: 'Cavaleiro Negro',
    element: 'dark',
    elementIcon: '🛡️',
    description: 'Sentinela impiedoso que patrulha as muralhas externas envolto em armadura de grafeno negro.',
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    rarity: 'Incomum',
    collectionId: 'knights',
    synthesisRate: 7,
    synthesisCap: 7000,
    marketValue: 110,
  },
  {
    templateId: 'card-knight-royal',
    name: 'Cavaleiro Real',
    element: 'light',
    elementIcon: '👑',
    description: 'Protetor jurado da linhagem imperial, empunha uma espada de plasma dourado.',
    image: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=800&auto=format&fit=crop&q=80',
    rarity: 'Incomum',
    collectionId: 'knights',
    synthesisRate: 8,
    synthesisCap: 8000,
    marketValue: 130,
  },
  {
    templateId: 'card-knight-arcane',
    name: 'Cavaleiro Arcano',
    element: 'arcane',
    elementIcon: '🔮',
    description: 'Mescla esgrima cibernética com runas arcanas digitais para romper barreiras.',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'knights',
    synthesisRate: 10,
    synthesisCap: 10000,
    marketValue: 190,
  },
  {
    templateId: 'card-knight-scarlet',
    name: 'Cavaleiro Escarlate',
    element: 'fire',
    elementIcon: '🩸',
    description: 'Vanguardista lendário da Ordem da Fênix, imune a pulsos térmicos.',
    image: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'knights',
    synthesisRate: 11,
    synthesisCap: 11000,
    marketValue: 220,
  },
  {
    templateId: 'card-knight-lunar',
    name: 'Cavaleiro Lunar',
    element: 'lunar',
    elementIcon: '🌙',
    description: 'Guerreiro silencioso que canaliza a luminosidade das três luas de Eldoria.',
    image: 'https://images.unsplash.com/photo-1532767153582-b1a0e5145009?w=800&auto=format&fit=crop&q=80',
    rarity: 'Épico',
    collectionId: 'knights',
    synthesisRate: 15,
    synthesisCap: 15000,
    marketValue: 450,
  },
  {
    templateId: 'card-knight-imperial',
    name: 'Cavaleiro Imperial',
    element: 'light',
    elementIcon: '⚜️',
    description: 'Supremo marechal do império eldoriano, comanda as legiões de cavaleiros autômatos.',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    rarity: 'Lendário',
    collectionId: 'knights',
    synthesisRate: 23,
    synthesisCap: 23000,
    marketValue: 1050,
  },
  {
    templateId: 'card-knight-celestial',
    name: 'Cavaleiro Celestial',
    element: 'celestial',
    elementIcon: '✨',
    description: 'Entidade lendária que descende das estrelas para intervir apenas no colapso de impérios.',
    image: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80',
    rarity: 'Mítico',
    collectionId: 'knights',
    synthesisRate: 31,
    synthesisCap: 31000,
    marketValue: 2300,
  },
];

/* ========================================================================
   COLEÇÃO 4: CRIATURAS DO ABISMO (8 CARTAS)
   ======================================================================== */
export const ABYSS_TEMPLATES: CardTemplate[] = [
  {
    templateId: 'card-abyss-devourer',
    name: 'Devorador',
    element: 'abyss',
    elementIcon: '👾',
    description: 'Monstruosidade voraz que consome dados brutos nas camadas mais profundas da rede.',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    rarity: 'Comum',
    collectionId: 'abyss',
    synthesisRate: 5,
    synthesisCap: 5000,
    marketValue: 60,
  },
  {
    templateId: 'card-abyss-colossus',
    name: 'Colosso Abissal',
    element: 'abyss',
    elementIcon: '🗿',
    description: 'Gigante petrificado de matéria escura que resiste a bombardeios energéticos pesados.',
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    rarity: 'Incomum',
    collectionId: 'abyss',
    synthesisRate: 7,
    synthesisCap: 7000,
    marketValue: 110,
  },
  {
    templateId: 'card-abyss-serpent',
    name: 'Serpente Sombria',
    element: 'dark',
    elementIcon: '🐍',
    description: 'Criatura serpentina que nada pelos oceanos de óleo criogênico dos reatores abissais.',
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    rarity: 'Incomum',
    collectionId: 'abyss',
    synthesisRate: 8,
    synthesisCap: 8000,
    marketValue: 125,
  },
  {
    templateId: 'card-abyss-demon',
    name: 'Demônio do Vazio',
    element: 'void',
    elementIcon: '👁️',
    description: 'Entidade consciente que sussurra falhas lógicas nos sistemas operacionais da Cidadela.',
    image: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'abyss',
    synthesisRate: 11,
    synthesisCap: 11000,
    marketValue: 210,
  },
  {
    templateId: 'card-abyss-kraken',
    name: 'Kraken',
    element: 'water',
    elementIcon: '🦑',
    description: 'Terror oceânico com tentáculos cibernéticos capazes de arrastar naves inteiras para a fossa abissal.',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'abyss',
    synthesisRate: 12,
    synthesisCap: 12000,
    marketValue: 230,
  },
  {
    templateId: 'card-abyss-leviathan',
    name: 'Leviatã',
    element: 'water',
    elementIcon: '🌊',
    description: 'O maior predador dos mares sombrios de NEXA, gera maremotos iônicos com sua barbatana colossal.',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    rarity: 'Épico',
    collectionId: 'abyss',
    synthesisRate: 16,
    synthesisCap: 16000,
    marketValue: 470,
  },
  {
    templateId: 'card-abyss-hydra',
    name: 'Hidra Negra',
    element: 'dark',
    elementIcon: '🐉',
    description: 'Besta de sete cabeças regenerativas forjadas no vácuo radioativo.',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
    rarity: 'Lendário',
    collectionId: 'abyss',
    synthesisRate: 24,
    synthesisCap: 24000,
    marketValue: 1150,
  },
  {
    templateId: 'card-abyss-king',
    name: 'Rei do Abismo',
    element: 'abyss',
    elementIcon: '👑',
    description: 'O soberano do desconhecido absoluto, domina todos os seres que rastejam na escuridão eterna.',
    image: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80',
    rarity: 'Mítico',
    collectionId: 'abyss',
    synthesisRate: 33,
    synthesisCap: 33000,
    marketValue: 2600,
  },
];

/* ========================================================================
   COLEÇÃO 5: MAGOS ELEMENTAIS (8 CARTAS)
   ======================================================================== */
export const MAGES_TEMPLATES: CardTemplate[] = [
  {
    templateId: 'card-mage-fire',
    name: 'Mago do Fogo',
    element: 'fire',
    elementIcon: '🔥',
    description: 'Invocador de tempestades de chamas que alimenta reatores com piromancia digital.',
    image: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?w=800&auto=format&fit=crop&q=80',
    rarity: 'Comum',
    collectionId: 'mages',
    synthesisRate: 5,
    synthesisCap: 5000,
    marketValue: 55,
  },
  {
    templateId: 'card-mage-ice',
    name: 'Mago do Gelo',
    element: 'ice',
    elementIcon: '❄️',
    description: 'Manipulador de fluxos térmicos negativos, resfria supercomputadores em combate.',
    image: 'https://images.unsplash.com/photo-1491002052546-bf38f186af56?w=800&auto=format&fit=crop&q=80',
    rarity: 'Comum',
    collectionId: 'mages',
    synthesisRate: 5,
    synthesisCap: 5000,
    marketValue: 55,
  },
  {
    templateId: 'card-mage-earth',
    name: 'Mago da Terra',
    element: 'earth',
    elementIcon: '⛰️',
    description: 'Ergue barreiras de silício e ferro cristalizado capazes de deter projéteis cinéticos.',
    image: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    rarity: 'Incomum',
    collectionId: 'mages',
    synthesisRate: 7,
    synthesisCap: 7000,
    marketValue: 110,
  },
  {
    templateId: 'card-mage-wind',
    name: 'Mago do Ar',
    element: 'wind',
    elementIcon: '💨',
    description: 'Canalizador de tempestades atmosféricas e ventos supersônicos em campos de força.',
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    rarity: 'Incomum',
    collectionId: 'mages',
    synthesisRate: 7,
    synthesisCap: 7000,
    marketValue: 110,
  },
  {
    templateId: 'card-mage-light',
    name: 'Mago da Luz',
    element: 'light',
    elementIcon: '✨',
    description: 'Emite fótons ultra-concentrados capazes de cegar matrizes de sensores inimigos.',
    image: 'https://images.unsplash.com/photo-1533158307587-828f0a76ef46?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'mages',
    synthesisRate: 10,
    synthesisCap: 10000,
    marketValue: 195,
  },
  {
    templateId: 'card-mage-shadow',
    name: 'Mago das Sombras',
    element: 'dark',
    elementIcon: '🌑',
    description: 'Tecelão de ilusões espectrais que dissolve vestígios de transações na rede de Eldoria.',
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'mages',
    synthesisRate: 11,
    synthesisCap: 11000,
    marketValue: 220,
  },
  {
    templateId: 'card-mage-arcane',
    name: 'Mago Arcano',
    element: 'arcane',
    elementIcon: '🔮',
    description: 'Mestre supremo das equações secretas que regem o código primordial do universo NEXA.',
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&auto=format&fit=crop&q=80',
    rarity: 'Épico',
    collectionId: 'mages',
    synthesisRate: 16,
    synthesisCap: 16000,
    marketValue: 460,
  },
  {
    templateId: 'card-mage-archmage',
    name: 'Arquimago',
    element: 'arcane',
    elementIcon: '⚡',
    description: 'O líder do conclave dos magos elementais. Comanda todos os seis elementos em sinergia perfeita.',
    image: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80',
    rarity: 'Lendário',
    collectionId: 'mages',
    synthesisRate: 25,
    synthesisCap: 25000,
    marketValue: 1200,
  },
];

/* ========================================================================
   COLEÇÃO 6: DEUSES ANTIGOS (8 CARTAS)
   ======================================================================== */
export const GODS_TEMPLATES: CardTemplate[] = [
  {
    templateId: 'card-god-war',
    name: 'Deus da Guerra',
    element: 'fire',
    elementIcon: '⚔️',
    description: 'Entidade titânica de conflito cujas lâminas energéticas infligem terror em qualquer arena.',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'gods',
    synthesisRate: 11,
    synthesisCap: 11000,
    marketValue: 220,
  },
  {
    templateId: 'card-god-moon',
    name: 'Deusa da Lua',
    element: 'lunar',
    elementIcon: '🌙',
    description: 'Divindade etérea que vela pelas noites cósmicas, curando guerreiros com névoa estelar.',
    image: 'https://images.unsplash.com/photo-1532767153582-b1a0e5145009?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'gods',
    synthesisRate: 12,
    synthesisCap: 12000,
    marketValue: 230,
  },
  {
    templateId: 'card-god-thunder',
    name: 'Deus do Trovão',
    element: 'lightning',
    elementIcon: '⚡',
    description: 'Comandante dos céus turbulentos, seus relâmpagos reiniciam servidores planetários.',
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    rarity: 'Épico',
    collectionId: 'gods',
    synthesisRate: 16,
    synthesisCap: 16000,
    marketValue: 490,
  },
  {
    templateId: 'card-god-sea',
    name: 'Deus do Mar',
    element: 'water',
    elementIcon: '🌊',
    description: 'Senhor dos mares e abismos líquidos, comanda correntes gravitacionais de planetas oceânicos.',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    rarity: 'Épico',
    collectionId: 'gods',
    synthesisRate: 16,
    synthesisCap: 16000,
    marketValue: 490,
  },
  {
    templateId: 'card-god-death',
    name: 'Deus da Morte',
    element: 'dark',
    elementIcon: '💀',
    description: 'O guardião do fim inevitável de processos. Encaminha memórias descartadas para o vácuo.',
    image: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80',
    rarity: 'Épico',
    collectionId: 'gods',
    synthesisRate: 17,
    synthesisCap: 17000,
    marketValue: 530,
  },
  {
    templateId: 'card-god-light',
    name: 'Deusa da Luz',
    element: 'light',
    elementIcon: '☀️',
    description: 'A encarnação do amanhecer galáctico, ilumina setores esquecidos com energia radiante pura.',
    image: 'https://images.unsplash.com/photo-1533158307587-828f0a76ef46?w=800&auto=format&fit=crop&q=80',
    rarity: 'Lendário',
    collectionId: 'gods',
    synthesisRate: 24,
    synthesisCap: 24000,
    marketValue: 1200,
  },
  {
    templateId: 'card-god-chaos',
    name: 'Deus do Caos',
    element: 'void',
    elementIcon: '🌀',
    description: 'Força primordial entrópica que quebra simetrias e engendra novas probabilidades quânticas.',
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&auto=format&fit=crop&q=80',
    rarity: 'Lendário',
    collectionId: 'gods',
    synthesisRate: 26,
    synthesisCap: 26000,
    marketValue: 1350,
  },
  {
    templateId: 'card-god-supreme',
    name: 'Deus Supremo',
    element: 'celestial',
    elementIcon: '👑',
    description: 'A consciência suprema do cosmos NEXA. Criador da matriz original e guardião de todas as leis.',
    image: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80',
    rarity: 'Mítico',
    collectionId: 'gods',
    synthesisRate: 35,
    synthesisCap: 35000,
    marketValue: 3000,
  },
];

/* ========================================================================
   COLEÇÃO 7: ENTIDADES CÓSMICAS (8 CARTAS)
   ======================================================================== */
export const COSMIC_TEMPLATES: CardTemplate[] = [
  {
    templateId: 'card-cosmic-guardian',
    name: 'Guardião Estelar',
    element: 'cosmic',
    elementIcon: '⭐',
    description: 'Patrulheiro de órbitas estelares encarregado de desviar meteoros de cidades satélites.',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    rarity: 'Incomum',
    collectionId: 'cosmic',
    synthesisRate: 8,
    synthesisCap: 8000,
    marketValue: 130,
  },
  {
    templateId: 'card-cosmic-comet',
    name: 'Cometa Vivo',
    element: 'cosmic',
    elementIcon: '☄️',
    description: 'Corpo celeste autoconsciente que cruza constelações semeando elementos raros no espaço.',
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'cosmic',
    synthesisRate: 11,
    synthesisCap: 11000,
    marketValue: 220,
  },
  {
    templateId: 'card-cosmic-solar',
    name: 'Entidade Solar',
    element: 'solar',
    elementIcon: '☀️',
    description: 'Filamento de plasma coronário inteligente que alimenta megassistemas de energia de fusão.',
    image: 'https://images.unsplash.com/photo-1533158307587-828f0a76ef46?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'cosmic',
    synthesisRate: 12,
    synthesisCap: 12000,
    marketValue: 240,
  },
  {
    templateId: 'card-cosmic-lunar',
    name: 'Entidade Lunar',
    element: 'lunar',
    elementIcon: '🌙',
    description: 'Espírito prateado que harmoniza as marés energéticas das estações espaciais periféricas.',
    image: 'https://images.unsplash.com/photo-1532767153582-b1a0e5145009?w=800&auto=format&fit=crop&q=80',
    rarity: 'Épico',
    collectionId: 'cosmic',
    synthesisRate: 15,
    synthesisCap: 15000,
    marketValue: 470,
  },
  {
    templateId: 'card-cosmic-devourer',
    name: 'Devorador de Mundos',
    element: 'void',
    elementIcon: '🪐',
    description: 'Abominação de massa gravitacional hiperdensa que atrai asteroides para seu núcleo escuro.',
    image: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80',
    rarity: 'Épico',
    collectionId: 'cosmic',
    synthesisRate: 17,
    synthesisCap: 17000,
    marketValue: 520,
  },
  {
    templateId: 'card-cosmic-voidlord',
    name: 'Senhor do Vazio',
    element: 'void',
    elementIcon: '🕳️',
    description: 'Comandante das regiões de gravidade zero onde a luz e as transmissões não conseguem escapar.',
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    rarity: 'Lendário',
    collectionId: 'cosmic',
    synthesisRate: 25,
    synthesisCap: 25000,
    marketValue: 1250,
  },
  {
    templateId: 'card-cosmic-being',
    name: 'Ser Cósmico',
    element: 'cosmic',
    elementIcon: '🌌',
    description: 'Constelação viva sintetizada a partir de milhões de estrelas mortas.',
    image: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    rarity: 'Lendário',
    collectionId: 'cosmic',
    synthesisRate: 26,
    synthesisCap: 26000,
    marketValue: 1300,
  },
  {
    templateId: 'card-cosmic-primordial',
    name: 'Entidade Primordial',
    element: 'celestial',
    elementIcon: '✨',
    description: 'A faísca do Big Bang contida em um vaso de cristal cibernético inviolável.',
    image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&auto=format&fit=crop&q=80',
    rarity: 'Mítico',
    collectionId: 'cosmic',
    synthesisRate: 35,
    synthesisCap: 35000,
    marketValue: 3200,
  },
];

/* ========================================================================
   COLEÇÃO 8: CAÇADORES (8 CARTAS)
   ======================================================================== */
export const HUNTERS_TEMPLATES: CardTemplate[] = [
  {
    templateId: 'card-hunter-novice',
    name: 'Caçador Novato',
    element: 'nature',
    elementIcon: '🏹',
    description: 'Rastreador iniciante equipado com arco de pulso eletromagnético e óculos de visão térmica.',
    image: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80',
    rarity: 'Comum',
    collectionId: 'hunters',
    synthesisRate: 5,
    synthesisCap: 5000,
    marketValue: 50,
  },
  {
    templateId: 'card-hunter-shadow',
    name: 'Caçador Sombrio',
    element: 'dark',
    elementIcon: '🗡️',
    description: 'Especialista em emboscadas na selva cibernética, usa camuflagem ativa refratária.',
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    rarity: 'Comum',
    collectionId: 'hunters',
    synthesisRate: 5,
    synthesisCap: 5000,
    marketValue: 60,
  },
  {
    templateId: 'card-hunter-arcane',
    name: 'Caçador Arcano',
    element: 'arcane',
    elementIcon: '🔮',
    description: 'Combina munições impregnadas de éter com rastreamento espectral de relíquias.',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    rarity: 'Incomum',
    collectionId: 'hunters',
    synthesisRate: 7,
    synthesisCap: 7000,
    marketValue: 115,
  },
  {
    templateId: 'card-hunter-dragonslayer',
    name: 'Caçador de Dragões',
    element: 'fire',
    elementIcon: '🐉',
    description: 'Veterano couraçado com escamas de dragão rubro, imune a baforadas de plasma de 5000°C.',
    image: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800&auto=format&fit=crop&q=80',
    rarity: 'Incomum',
    collectionId: 'hunters',
    synthesisRate: 8,
    synthesisCap: 8000,
    marketValue: 135,
  },
  {
    templateId: 'card-hunter-lunar',
    name: 'Caçador Lunar',
    element: 'lunar',
    elementIcon: '🌙',
    description: 'Franco-atirador que opera em condições de gravidade lunar com rifle de disparo táquion.',
    image: 'https://images.unsplash.com/photo-1532767153582-b1a0e5145009?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'hunters',
    synthesisRate: 10,
    synthesisCap: 10000,
    marketValue: 200,
  },
  {
    templateId: 'card-hunter-royal',
    name: 'Caçador Real',
    element: 'light',
    elementIcon: '👑',
    description: 'Guardião da fauna nobre dos jardins imperiais de Eldoria, treinado para caçar nobres corrompidos.',
    image: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=800&auto=format&fit=crop&q=80',
    rarity: 'Raro',
    collectionId: 'hunters',
    synthesisRate: 11,
    synthesisCap: 11000,
    marketValue: 225,
  },
  {
    templateId: 'card-hunter-ghost',
    name: 'Caçador Fantasma',
    element: 'void',
    elementIcon: '👻',
    description: 'Atravessa obstáculos físicos sem deixar assinaturas térmicas, caçando alvos através de paredes.',
    image: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80',
    rarity: 'Épico',
    collectionId: 'hunters',
    synthesisRate: 15,
    synthesisCap: 15000,
    marketValue: 480,
  },
  {
    templateId: 'card-hunter-master',
    name: 'Mestre Caçador',
    element: 'nature',
    elementIcon: '🦅',
    description: 'O lendário líder de todas as guildas de caça de NEXA. Nunca errou um disparo de plasma.',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    rarity: 'Lendário',
    collectionId: 'hunters',
    synthesisRate: 23,
    synthesisCap: 23000,
    marketValue: 1180,
  },
];

/* ========================================================================
   AGREGADO TOTAL DE TODAS AS 60 CARTAS
   ======================================================================== */
export const ALL_CARD_TEMPLATES: CardTemplate[] = [
  ...GUARDIANS_TEMPLATES,
  ...DRAGONS_TEMPLATES,
  ...KNIGHTS_TEMPLATES,
  ...ABYSS_TEMPLATES,
  ...MAGES_TEMPLATES,
  ...GODS_TEMPLATES,
  ...COSMIC_TEMPLATES,
  ...HUNTERS_TEMPLATES,
];

/* ========================================================================
   AS 8 COLEÇÕES COMPLETAS DO ECOSSISTEMA NEXA
   ======================================================================== */
export const COLLECTIONS_DATA: CardCollection[] = [
  {
    id: 'guardians',
    name: 'Os Quatro Guardiões',
    tagline: 'As 4 forças elementais ancestrais do ecossistema NEXA',
    description: 'Uma das mais reverenciadas assembléias de poder da Cidadela. Cada guardião comanda uma força natural primordial e sintetiza NEX de forma contínua em seu reator interno.',
    bannerImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1200&auto=format&fit=crop&q=80',
    cardTemplates: GUARDIANS_TEMPLATES,
    rewardBoxName: 'Caixa dos Quatro Guardiões',
    rewardDescription: 'Concede 1.500 NEX líquidos + Pacote de 100 Fragmentos de Maestria dos Guardiões para a sua conta.',
  },
  {
    id: 'dragons',
    name: 'Dragões Ancestrais',
    tagline: 'Soberanos das eras mitológicas e titãs alados de fogo e éter',
    description: 'Gigantes imortais que governaram as regiões vulcânicas e céus galácticos antes da fundação de Neo-Tokyo. Suas escamas canalizam frequências de poder extraordinárias.',
    bannerImage: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1200&auto=format&fit=crop&q=80',
    cardTemplates: DRAGONS_TEMPLATES,
    rewardBoxName: 'Caixa Dragões Ancestrais',
    rewardDescription: 'Concede 2.500 NEX líquidos + Pacote de 100 Fragmentos Draconianos Celestiais.',
  },
  {
    id: 'knights',
    name: 'Cavaleiros de Eldoria',
    tagline: 'A ordem de cavalaria cibernética protetora dos setores imperiais',
    description: 'Guerreiros de honra implacável forjados nas academias de alta tecnologia de Eldoria. Unem tradição marcial arcaica a blindagens de plasma de última geração.',
    bannerImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=1200&auto=format&fit=crop&q=80',
    cardTemplates: KNIGHTS_TEMPLATES,
    rewardBoxName: 'Caixa Cavaleiros de Eldoria',
    rewardDescription: 'Concede 2.000 NEX líquidos + Insígnia Honorária de Eldoria.',
  },
  {
    id: 'abyss',
    name: 'Criaturas do Abismo',
    tagline: 'Monstruosidades das profundezas quânticas e fossas oceânicas',
    description: 'Entidades forjadas na pressão esmagadora do fundo dos mares e no vazio da matéria escura. Possuem índices de produção energética assustadoramente altos.',
    bannerImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
    cardTemplates: ABYSS_TEMPLATES,
    rewardBoxName: 'Caixa Criaturas do Abismo',
    rewardDescription: 'Concede 2.200 NEX líquidos + 100 Fragmentos do Rei do Abismo.',
  },
  {
    id: 'mages',
    name: 'Magos Elementais',
    tagline: 'Eruditos das leis fundamentais da termodinâmica e do arcano',
    description: 'Mestres do código computacional que rege os elementos. Conseguem moldar fogo, gelo, terra, luz e sombra através de suas matrizes de encantamento neural.',
    bannerImage: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?w=1200&auto=format&fit=crop&q=80',
    cardTemplates: MAGES_TEMPLATES,
    rewardBoxName: 'Caixa Magos Elementais',
    rewardDescription: 'Concede 2.000 NEX líquidos + 100 Fragmentos Arcanos de Arquimago.',
  },
  {
    id: 'gods',
    name: 'Deuses Antigos',
    tagline: 'Panteão de deidades cósmicas que moldaram as leis da realidade',
    description: 'As entidades veneradas pelas primeiras civilizações inteligentes. Cada deus comanda um conceito primordial absoluto da existência.',
    bannerImage: 'https://images.unsplash.com/photo-1533158307587-828f0a76ef46?w=1200&auto=format&fit=crop&q=80',
    cardTemplates: GODS_TEMPLATES,
    rewardBoxName: 'Caixa Deuses Antigos',
    rewardDescription: 'Concede 3.500 NEX líquidos + Coroa de Deus Supremo com 100 Fragmentos Divinos.',
  },
  {
    id: 'cosmic',
    name: 'Entidades Cósmicas',
    tagline: 'Fenômenos astrofísicos autoconscientes e devoradores estelares',
    description: 'Nascidos no coração de nebulosas e buracos negros, estes seres transcendem a biologia padrão. São os maiores conversores de energia cósmica em NEX.',
    bannerImage: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=1200&auto=format&fit=crop&q=80',
    cardTemplates: COSMIC_TEMPLATES,
    rewardBoxName: 'Caixa Entidades Cósmicas',
    rewardDescription: 'Concede 3.200 NEX líquidos + Núcleo Estelar Cósmico Primordial.',
  },
  {
    id: 'hunters',
    name: 'Caçadores',
    tagline: 'Rastreadores lendários especializados em predar feras e relíquias',
    description: 'A guilda mais temida e respeitada das fronteiras. Armados com armas de longo alcance táquion e astúcia sem paralelos em qualquer bioma selvagem.',
    bannerImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
    cardTemplates: HUNTERS_TEMPLATES,
    rewardBoxName: 'Caixa Caçadores',
    rewardDescription: 'Concede 2.000 NEX líquidos + Insígnia do Mestre Caçador.',
  },
];

/* ========================================================================
   HELPER UTILITIES
   ======================================================================== */
export function getTemplateById(templateId: string): CardTemplate | undefined {
  return ALL_CARD_TEMPLATES.find((t) => t.templateId === templateId);
}

export function getTemplatesByCollection(collectionId: string): CardTemplate[] {
  return ALL_CARD_TEMPLATES.filter((t) => t.collectionId === collectionId);
}

export function getTemplatesByRarity(rarity: Rarity, pool?: CardTemplate[]): CardTemplate[] {
  const source = pool || ALL_CARD_TEMPLATES;
  return source.filter((t) => t.rarity === rarity);
}
