import { SeasonConfig } from '../types';

export const CURRENT_SEASON: SeasonConfig = {
  id: 'season-1',
  name: 'ASCENSÃO',
  editionLabel: 'Temporada 1: Despertar Cibernético',
  slogan: 'Conquiste a arena, forje relíquias e ascenda ao topo da ordem cibernética.',
  startDate: '2026-03-01',
  endDate: '2026-04-30',
  maxLevel: 20,
  xpPerLevel: 1000,
  rewards: [
    { level: 1, type: 'NEX', value: 500, name: '500 Moedas NEX', isPremium: false },
    { level: 2, type: 'NXA', value: 50, name: '50 Tokens NXA', isPremium: false },
    { level: 3, type: 'ITEM', value: 'item_box_common', name: 'Caixa de Suprimentos Comum', isPremium: false },
    { level: 4, type: 'NEX', value: 1000, name: '1.000 Moedas NEX', isPremium: false },
    { level: 5, type: 'TITLE', value: 'Iniciado Cibernético', name: 'Título: [Iniciado]', isPremium: true },
    { level: 6, type: 'NXA', value: 100, name: '100 Tokens NXA', isPremium: false },
    { level: 7, type: 'ITEM', value: 'armor_quantum', name: 'Peitoral de Nanofibra Incomum', isPremium: false },
    { level: 8, type: 'NEX', value: 2000, name: '2.000 Moedas NEX', isPremium: false },
    { level: 9, type: 'NXA', value: 150, name: '150 Tokens NXA', isPremium: true },
    { level: 10, type: 'ITEM', value: 'weapon_plasma', name: 'Espada de Íons Rara', isPremium: false },
    { level: 11, type: 'NEX', value: 3500, name: '3.500 Moedas NEX', isPremium: false },
    { level: 12, type: 'NXA', value: 250, name: '250 Tokens NXA', isPremium: true },
    { level: 13, type: 'ITEM', value: 'artifact_chronos', name: 'Cálice Temporal Épico', isPremium: false },
    { level: 14, type: 'NEX', value: 5000, name: '5.000 Moedas NEX', isPremium: false },
    { level: 15, type: 'TITLE', value: 'Gladiador do Vácuo', name: 'Título: [Gladiador]', isPremium: true },
    { level: 16, type: 'NXA', value: 500, name: '500 Tokens NXA', isPremium: false },
    { level: 17, type: 'NEX', value: 8000, name: '8.000 Moedas NEX', isPremium: false },
    { level: 18, type: 'NXA', value: 750, name: '750 Tokens NXA', isPremium: true },
    { level: 19, type: 'ITEM', value: 'skin_cyber_phantom', name: 'Skin Lendária Fantasma Neon', isPremium: true },
    { level: 20, type: 'TITLE', value: 'Soberano da Ascensão', name: 'Emblema Mítico & Título Soberano', isPremium: true },
  ],
  challenges: [
    {
      id: 'ch-1',
      title: 'Batismo de Fogo',
      description: 'Vença 5 partidas na Arena de Batalha.',
      xpReward: 400,
      progress: 3,
      maxProgress: 5,
      isCompleted: false,
      category: 'battle',
    },
    {
      id: 'ch-2',
      title: 'Comerciante Sagaz',
      description: 'Realize pelo menos 1 compra ou venda no Marketplace.',
      xpReward: 300,
      progress: 1,
      maxProgress: 1,
      isCompleted: true,
      category: 'market',
    },
    {
      id: 'ch-3',
      title: 'Mestre da Forja',
      description: 'Efetue 2 fusões de itens no Reator.',
      xpReward: 600,
      progress: 0,
      maxProgress: 2,
      isCompleted: false,
      category: 'fusion',
    },
    {
      id: 'ch-4',
      title: 'Guerreiro Implacável',
      description: 'Alcance 10 vitórias totais na temporada.',
      xpReward: 1000,
      progress: 6,
      maxProgress: 10,
      isCompleted: false,
      category: 'battle',
    },
    {
      id: 'ch-5',
      title: 'Arsenal Pesado',
      description: 'Colecione ao menos 1 item de raridade Épica ou superior.',
      xpReward: 800,
      progress: 1,
      maxProgress: 1,
      isCompleted: true,
      category: 'collection',
    },
  ],
};
